### ISSUE TITLE
代理环境配置，mac

### ISSUE THREAD

**Issue by CarGuo** [CarGuo/GSYGithubAppFlutter#13]
![63da34a5-f50b-4da4-89f3-c2db964f045f](https://user-images.githubusercontent.com/10770362/43753169-fffca1a6-9a36-11e8-96d6-9f1ebd2d3fc9.png)

**Comment by CarGuo** [comment]
flutter 环境配置

1、 sdk

```
git clone -b beta https://github.com/flutter/flutter.git

git checkout v0.5.7 //切换到.0.5.7版本
```

2、配置环境代理
```
win配置到环境变量
mac配置到 .bash_profile 文件（用户名目录下的隐藏文件，可以通过命令行 open .bash_profile 打包）
```

3、检查环境

重新打开命令行并执行

```
flutter doctor
```


4、同步项目的包
```
flutter packages get


flutter packages upgrade
```


5、androd和ios环境是否配置

**Comment by Captain-Justin** [comment]
materialTapTargetSize: MaterialTapTargetSize.shrinkWrap
 undefined name MaterialTapTargetSize

**Comment by CarGuo** [comment]
看一下你本地的flutter sdk是什么版本

**Comment by tonyhelloworld** [comment]
materialTapTargetSize: MaterialTapTargetSize.shrinkWrap 这个是用来防止溢出的吗？尽可能的缩小控件吗

**Comment by CarGuo** [comment]
@tonyhelloworld   
```
/// Shrinks the tap target size to the minimum provided by the Material
/// specification.
```

![5b7d1969e4b07b78518780e6](https://user-images.githubusercontent.com/10770362/44451082-39e35280-a625-11e8-9e74-7b44c19ff332.png)

**Comment by tonyhelloworld** [comment]
@CarGuo 不太明白

**Comment by tonyhelloworld** [comment]
大佬，在小于5寸手机下，draw层下的就会溢出 ，本月统计那里也是溢出。
https://github.com/CarGuo/GSYGithubAppFlutter/blob/master/lib/widget/HomeDrawer.dart#LC82 这个建议加个可滚动的控件

**Comment by CarGuo** [comment]
这个控件其实就是可滚动的，方便截个图看看这几个问题的效果不？

**Comment by CarGuo** [comment]
https://github.com/flutter/flutter/issues/20809

**Comment by CarGuo** [comment]
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

**Comment by joexchen** [comment]
接口Http status error [422]

**Comment by CarGuo** [comment]
@joexchen 你需要配置正确你github 申请的应用id和sercet

**Comment by joexchen** [comment]
配置了的，我能正常登陆GitHub网页端，但是跑起来，就报422

**Comment by MorLightJ** [comment]
> 配置了的，我能正常登陆GitHub网页端，但是跑起来，就报422

我也遇到相同的问题，请问你是否已经解决这个问题？？

**Comment by CarGuo** [comment]
目前已知442问题是由于 page 请求超出了 数据的最大page 导致的

**Comment by zdllyzs** [comment]
有一个和本issue无关的问题想请教一下楼主，请问楼主的main.dart是怎么跳转到WelcomePage的，找了一下好像没有在main.dart发现Navigator有关代码，也没有在MaterialApp中配置home属性，但是打开应用就回进入欢迎页==flutter基础不好，还请楼主指点一二QAQ

**Comment by ufolux** [comment]
I met a problem that api returned exception 422.

**Comment by q13945951476** [comment]
大佬帮忙看下呗，什么原因

Error output from CocoaPods:
↳
    [!] The version of CocoaPods used to generate the lockfile (1.5.3) is higher than the version of the current executable (1.5.0). Incompatibility issues may arise.


    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone XR.

**Comment by q13945951476** [comment]
Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "lottie-ios":
      In snapshot (Podfile.lock):
        lottie-ios (= 2.5.2)

      In Podfile:
        flutter_lottie (from `.symlinks/plugins/flutter_lottie/ios`) was resolved to 0.0.1, which depends on
          lottie-ios

    It seems like you've changed the constraints of dependency `lottie-ios` inside your development pod `flutter_lottie`.
    You should run `pod update lottie-ios` to apply changes you've made.

<img width="1089" alt="wenti1" src="https://user-images.githubusercontent.com/2841849/57506219-c6f24700-732d-11e9-8ec5-e166ad0726e5.png">

**Comment by CarGuo** [comment]
@q13945951476 首先确定你flutter packages get 成功了，本地都已经有所有包了，然后再执行，如果还有问题升级下你本地的 pod 命令版本，我刚刚试了clone一个新的执行没有问题

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/419  

flutter packages get 提示 git 失败原因：
比如

win 是在 `C:\Users\xxxxx\AppData\Roaming\Pub\Cache` 路径下有 `git` 目录，如果存在某次 package get 失败之后，`git` 下目录会存在，然后出现这个异常。 可以删除 git 目录有重新 flutter packages get

mac 目录在` ~/.pub-cache`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/63   

[ignoreconfigdart 找不到问题](https://github.com/CarGuo/GSYGithubAppFlutter#3重点你需要自己在libcommonconfig目录下-创建一个ignoreconfigdart文件然后输入你申请的github-client_id-和-client_secret)

**Comment by flutePeak** [comment]
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

**Comment by flutePeak** [comment]
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone Xʀ.

按照这个报错，执行了命令，还是报这个

**Comment by CarGuo** [comment]
@flutePeak CocoaPods 1.6.1 版本

**Comment by flutePeak** [comment]
@CarGuo 1.7.2版本太高了吗？ 我目前版本是1.7.2

**Comment by flutePeak** [comment]
@CarGuo 谢谢大大，我成功跑起来了，，我发现是我笔记本有缓存，之前老版本的一直影响着。。全删干净之后，1.7.2跑起来了

**Comment by flutePeak** [comment]
@CarGuo 我跑起来项目了，运行看着也没问题，但是时不时就进debug，说是报错了，有的地方为空，或者什么的。但是放行后，看着一切正常。。是我跑失败了，还是代码有问题？或者是我编辑器的锅，编辑器是VScode

**Comment by algate** [comment]
运行起来了，界面展示
![图片](https://user-images.githubusercontent.com/10138191/60262617-27a30680-9911-11e9-89c1-eb4a230f5bf7.png)
怎么进入应用呢

**Comment by algate** [comment]
项目运行起来了
界面展示如下：
![图片](https://user-images.githubusercontent.com/10138191/60262813-b152d400-9911-11e9-9475-ed7db69fc012.png)
如何进入应用呢！

**Comment by CarGuo** [comment]
@algate 然后会进入登陆页，如果卡在这里说明没有运行成功，你下载打包好的apk就知道了

**Comment by q815956089** [comment]
请求异常: DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timeout[15000ms]

**Comment by CarGuo** [comment]
@q815956089  Connecting timeout ，换个网络环境试试，15 秒超时

**Comment by q815956089** [comment]
感谢回复，还是不行，报错


I/flutter (23539): base64Str login ODE1OTU2MDg5QHFxLmNvbTpzaWxlbmNlOTgyNjY0
I/flutter (23539): 请求url：https://api.github.com/authorizations
I/flutter (23539): 请求头: {Authorization: Basic ODE1OTU2MDg5QHFxLmNvbTpzaWxlbmNlOTgyNjY0}
I/flutter (23539): 请求参数: {"scopes":["user","repo","gist","notifications"],"note":"admin_script","client_id":"89e41d78ac8d250ed660","client_secret":"db8bdc5aceb88b4a94665ef29





------------------ 原始邮件 ------------------
发件人: "Shuyu Guo"<notifications@github.com>;
发送时间: 2019年7月5日(星期五) 上午9:40
收件人: "CarGuo/GSYGithubAppFlutter"<GSYGithubAppFlutter@noreply.github.com>;
抄送: "815956089"<815956089@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CarGuo/GSYGithubAppFlutter] 项目运行环境配置 (#13)




@q815956089  Connecting timeout ，换个网络环境试试，15 秒超时

**Comment by Chenthy** [comment]
大佬，为什么我mac 清除了pub-cache里的git 目录了 ，再运行packages get还是会出现 Could not find a file named "pubspec.yaml" in https://github.com/CarSmallGuo/flutter_lottie.git 3adb18f2e2a45b8dbdebc0437e9a4db3f6ff32b8.

**Comment by xiaorong1176** [comment]
编译报错：
master/ios/Runner/GeneratedPluginRegistrant.m
'android_intent/AndroidIntentPlugin.h' file not found

**Comment by yin87** [comment]
点击Get dependencies获取依赖包报错了。。。其他项目可以获取到依赖包
<img width="675" alt="2" src="https://user-images.githubusercontent.com/12492884/62667740-9f0d9080-b9bb-11e9-9ff5-a49cc326820b.png">
<img width="324" alt="1" src="https://user-images.githubusercontent.com/12492884/62667743-a2088100-b9bb-11e9-880d-27fcb975c9f5.png">

**Comment by yin87** [comment]
Working dir: E:\flutter_app\GSYGithubAppFlutter
D:\app\flutter\bin\cache\dart-sdk\bin\pub.bat get
活动代码页: 936
Resolving dependencies...
Cannot find a Git executable.
Please ensure Git is correctly installed.
Process finished with exit code 1

**Comment by CarGuo** [comment]
@yin87 log 上不是写着了么，没有找到 git 啊·····

**Comment by yin87** [comment]
> @yin87 log 上不是写着了么，没有找到 git 啊·····

但是，不知道为什么会找不到。。。因为其他项目可以找到。。。百度了下也没找到解决方案。。。

**Comment by yin87** [comment]
> @yin87 log 上不是写着了么，没有找到 git 啊·····

这是另外一个项目，正常。。。
Working dir: E:\flutter_app\flutter_trip-master
D:\app\flutter\bin\cache\dart-sdk\bin\pub.bat get
活动代码页: 936
Resolving dependencies...
Got dependencies!
Process finished with exit code 0

**Comment by CarGuo** [comment]
其他项目不一定 pubspec.yaml 使用 git 依赖，而 GSY 使用了 git 依赖 @yin87

**Comment by yin87** [comment]
多谢耐心的回答，git有配置，下图显示出了版本号
<img width="220" alt="1" src="https://user-images.githubusercontent.com/12492884/62670077-7938b980-b9c4-11e9-9343-e9c53ba14ea8.png">

**Comment by CarGuo** [comment]
@yin87 那就很诡异了，没遇到过这种情况

**Comment by yin87** [comment]
> @yin87 那就很诡异了，没遇到过这种情况

把下面代码注释了，packages get成功了
<img width="556" alt="1" src="https://user-images.githubusercontent.com/12492884/62686327-1ad8fe80-b9f7-11e9-8f52-a179a3299bd8.png">

**Comment by CarGuo** [comment]
@yin87 https://github.com/CarGuo/GSYGithubAppFlutter/issues/13#issuecomment-496960086

**Comment by tongyangsheng** [comment]
![image](https://user-images.githubusercontent.com/32046282/62932640-1ba4d280-bdf3-11e9-921f-9450cead93b7.png)
import 'package:gsy_github_app_flutter/common/config/ignoreConfig.dart'; 这一行报错 是因为没有获取到这个包吗？可是 flutter packages get没有报错啊

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppFlutter/issues/63 @tongyangsheng 看readme

**Comment by tongyangsheng** [comment]
@CarGuo 看到了！谢谢！博主在线频率好评 哈哈哈哈哈哈

**Comment by longdw** [comment]
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
同样的错误

**Comment by houko** [comment]
flutter 都1.9了,不考虑升级下吗

**Comment by CarGuo** [comment]
@houko 兼容的

**Comment by houko** [comment]
@CarGuo 我的想法是更到新版本可以给大家提供一下新版本的迭代思路

**Comment by chindeng** [comment]
> DioError [DioErrorType.RESPONSE]：Http状态错误[401] 
> {“消息”：“需要身份验证”，“ documentation_url”：“ [https://developer.github.com/v3”}](https://developer.github.com/v3%22%7D)
> 出现这个问题是什么原因？
> 已经按照@manburenshenglu注册了应用程序，输入了正确的ID和密码，但还是不行。

@CarGuo

**Comment by CarGuo** [comment]
@chenxihub 如果是自己编译的，确定你申请的 github api 的 appId 是 sercet 是否正确。
然后确定使用 github 用户名 和 密码登陆，网络正常，暂时不支持开启了两次认证的账号。

**Comment by houko** [comment]
@CarGuo 支持IOS吗?我试了一下ios编译出错

**Comment by CarGuo** [comment]
@houko 报错？我这边没报错呢，你的错误是什么，我的 pod 版本是 1.6.1

**Comment by chindeng** [comment]
> > DioError [DioErrorType.RESPONSE]：Http状态错误[401] 
> > {“消息”：“需要身份验证”，“ documentation_url”：“ [https://developer.github.com/v3”}](https://developer.github.com/v3%22%7D) 
> > 出现这个问题是什么原因？
> > 已经按照@manburenshenglu注册了应用程序，输入了正确的ID和密码，但还是不行。
> 
> @CarGuo

@CarGuo 问题已经解决，原因有两个，一个是没有安装GitHub应用程序，另一个就是在flutter程序运行后出现的登录界面输入了错误的信息，正确的应该是在上面输入GitHub账户和密码

**Comment by houko** [comment]
![1](https://user-images.githubusercontent.com/12625278/65672660-5a7da780-e084-11e9-80cc-ee2c032bc5e9.gif)

这是什么骚操作?

**Comment by CarGuo** [comment]
@houko 额？什么问题？还有你这是公布你的账号密码么······😂

**Comment by houko** [comment]
> @houko 额？什么问题？还有你这是公布你的账号密码么······😂

我随便按的，输什么都能登陆

**Comment by CarGuo** [comment]
@houko 这就有点牛逼了，我这里错误应该会提示错误的哇。

**Comment by houko** [comment]
> > @houko 额？什么问题？还有你这是公布你的账号密码么······😂
> 
> 我随便按的，输什么都能登陆
UserDao.login传进去的账号密码没有做校验啊

**Comment by houko** [comment]
你删我评论干啥啊 🐖

**Comment by CarGuo** [comment]
@houko 这个 pin issue 主要保留一些关键的回复

**Comment by sunimpulse** [comment]
> Android dependency 'androidx.arch.core:core-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution

**Comment by sunimpulse** [comment]
> Android dependency 'androidx.arch.core:core-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution

**Comment by CarGuo** [comment]
Flutter SDK 1.12.xx 版本目前请切换 dev_next 分支

**Comment by CarGuo** [comment]
flutter 环境配置

1、 sdk

```
git clone -b stable https://github.com/flutter/flutter.git
```

2、配置环境代理

```
win配置到环境变量

mac配置到 .bash_profile 文件（用户名目录下的隐藏文件，可以通过命令行 open .bash_profile 打包），新版的系统需要配置到 zsh 。

```

3、检查环境

重新打开命令行并执行

```
flutter doctor
```


4、同步项目的包
```
flutter packages get

```


5、androd和ios环境是否配置

**Comment by CarGuo** [comment]
1.17 之后，1.20 开始 CocoaPods 需要 1.8.0 以上，如果旧版本项目可能还需要更新或者重新生成 Podfile 文件

**Comment by CarGuo** [comment]
已兼容 1.22.1 版本运行

**Comment by veryitman** [comment]
ReadMe里面的文章打开一片空白。

**Comment by CarGuo** [comment]
@veryitman  已经更新，原有地址可能因为掘金升级过期了

**Comment by veryitman** [comment]
> @veryitman 已经更新，原有地址可能因为掘金升级过期了

好的，感谢。

**Comment by slowButstudy** [comment]
<img width="419" alt="截屏2021-05-09 22 37 56" src="https://user-images.githubusercontent.com/11956123/117576136-3cf53880-b117-11eb-8e94-6f4813cab053.png">
大佬 请问下这两个文件缺失怎么解决 ，运行环境配置阶段：flutter pub get 后出现这两个文件缺失问题 ，实在不知道该怎么解决了 求指点

**Comment by Studying-HL** [comment]
项目配置成功后 vsCode运行失败 错误信息如下图
<img width="1218" alt="截屏2021-05-15 19 42 00" src="https://user-images.githubusercontent.com/11956123/118359556-985f7480-b5b6-11eb-9d03-f751529870bc.png">
<img width="1216" alt="截屏2021-05-15 19 42 13" src="https://user-images.githubusercontent.com/11956123/118359559-9b5a6500-b5b6-11eb-8559-26b421b75db7.png">

**Comment by JasonOnlyLove** [comment]
Authorization callback URL 一栏必须填入 gsygithubapp://authed ，回调地址没有用，报超时错误 net::ERR_CONNECTION_TIMED_OUT

**Comment by liuchao0739** [comment]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/88572042/211964823-8d63b5dd-d685-496a-b902-18f43aba2f6b.png">

请问下这是什么原因？

**Comment by CarGuo** [comment]
如图，连接失败，给你的 android gradle 配置代理
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/10770362/211989571-8a3a6ca6-8695-4492-8fb3-5f800f62907d.png">

**Comment by kiss718867** [comment]
跑不起来，请大佬看一下这是因为什么
![CEBB0F01-AEF9-454F-9280-CA63B3B19EB6](https://github.com/CarGuo/gsy_github_app_flutter/assets/9364258/822a14cf-2b46-430a-9724-921b407c6435)

**Comment by CarGuo** [comment]
@kiss718867  看 readme

**Comment by kiss718867** [comment]
@CarGuo 大佬再看看，按照 readme 操作，gsy_github_app_flutter 跑起来了，gsy_flutter_demo 还是报这个错。。
![2FD2D139-74C2-4DFB-A142-837855B98CAB](https://github.com/CarGuo/gsy_github_app_flutter/assets/9364258/77727e1c-99c1-4193-9f18-188bd8b91dba)

**Comment by CarGuo** [comment]
@kiss718867 你看看本地 flutter 的 sdk 版本是不是 3.10

**Comment by kiss718867** [comment]
> @kiss718867 你看看本地 flutter 的 sdk 版本是不是 3.10

之前 3.12，切到 3.10 可以了，感谢

**Comment by wolfuture** [comment]
请求url：https://api.github.com/authorizations POST
请求异常: DioException [bad response]: This exception was thrown because the response has a status code of 404

**Comment by CarGuo** [comment]
> https://api.github.com/authorizations

一般是 requestParams 不对，例如 CLIENT_ID 和  CLIENT_SECRET 并且 Authorization callback URL 一栏必须填入 gsygithubapp://authed

**Comment by xingxdxxd** [comment]
Pub get提示找不到flare_flutter，这个怎么解决啊
log：Because gsy_github_app_flutter depends on flare_flutter from git which doesn't exist (Could not find git ref 'd9c4ca55cbea3f283491679847ff1e9b4bc74192'.), version solving failed.
Failed to update packages.

**Comment by CarGuo** [comment]
![image](https://github.com/user-attachments/assets/a0b45250-dddc-4785-8108-2f9dd76afb9f)

**Comment by jones655** [comment]
[麻烦看下，代码报错/C:/Users/12473/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio_web_adapter-2.0.0/lib/src/dio_impl.dart:29:5: Error: Type 'FileMode' not found.  
    FileMode? fileAccessMode, // 添加缺少的参数
    ^^^^^^^^
lib/widget/gsy_tabs.dart:141:49: Error: A value of type 'TabBarThemeData' can't be assigned to a variable of type 'TabBarTheme'.
 - 'TabBarThemeData' is from 'package:flutter/src/material/tab_bar_theme.dart'
 ('/E:/Program%20Files/Android/flutter_windows_3.27.1-stable/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
 - 'TabBarTheme' is from 'package:flutter/src/material/tab_bar_theme.dart'
 ('/E:/Program%20Files/Android/flutter_windows_3.27.1-stable/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
    final TabBarTheme tabBarTheme = TabBarTheme.of(context);
                                                ^
lib/widget/gsy_tabs.dart:739:49: Error: A value of type 'TabBarThemeData' can't be assigned to a variable of type 'TabBarTheme'.
 - 'TabBarThemeData' is from 'package:flutter/src/material/tab_bar_theme.dart'
 ('/E:/Program%20Files/Android/flutter_windows_3.27.1-stable/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
 - 'TabBarTheme' is from 'package:flutter/src/material/tab_bar_theme.dart'
 ('/E:/Program%20Files/Android/flutter_windows_3.27.1-stable/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
    final TabBarTheme tabBarTheme = TabBarTheme.of(context);
                                                ^
lib/widget/gsy_tabs.dart:981:49: Error: A value of type 'TabBarThemeData' can't be assigned to a variable of type 'TabBarTheme'.
 - 'TabBarThemeData' is from 'package:flutter/src/material/tab_bar_theme.dart'
 ('/E:/Program%20Files/Android/flutter_windows_3.27.1-stable/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
 - 'TabBarTheme' is from 'package:flutter/src/material/tab_bar_theme.dart'
 ('/E:/Program%20Files/Android/flutter_windows_3.27.1-stable/flutter/packages/flutter/lib/src/material/tab_bar_theme.dart').
    final TabBarTheme tabBarTheme = TabBarTheme.of(context);
                                                ^
/C:/Users/12473/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_slidable-3.1.1/lib/src/notifications_old.dart:88:23: Error: The method       
'hashValues' isn't defined for the class 'SlidableRatioNotification'.
 - 'SlidableRatioNotification' is from 'package:flutter_slidable/src/notifications_old.dart'
 ('/C:/Users/12473/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_slidable-3.1.1/lib/src/notifications_old.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
  int get hashCode => hashValues(tag, ratio);
                      ^^^^^^^^^^
/C:/Users/12473/AppData/Local/Pub/Cache/git/Flare-Flutter-ab41281006402485ff7326d0c58134f451a0de3a/flare_flutter/lib/provider/asset_flare.dart:25:23: 
Error: The method 'hashValues' isn't defined for the class 'AssetFlare'.
 - 'AssetFlare' is from 'package:flare_flutter/provider/asset_flare.dart'
 ('/C:/Users/12473/AppData/Local/Pub/Cache/git/Flare-Flutter-ab41281006402485ff7326d0c58134f451a0de3a/flare_flutter/lib/provider/asset_flare.dart').  
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
  int get hashCode => hashValues(bundle, name);
                      ^^^^^^^^^^
/C:/Users/12473/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio_web_adapter-2.0.0/lib/src/dio_impl.dart:29:5: Error: 'FileMode' isn't a type.    
    FileMode? fileAccessMode, // 添加缺少的参数
    ^^^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling
file:///C:/Users/12473/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/dio_web_adapter-2.0.0/lib/src/dio_impl.dart, which contains the type:
FunctionType(Future<Response<dynamic>> Function(String, dynamic, {cancelToken: CancelToken?, data: Object?, deleteOnError: bool, fileAccessMode:      
<invalid>, lengthHeader: String, onReceiveProgress: void Function(int, int)?, onSendProgress: void Function(int, int)?, options: Options?,
queryParameters: Map<String, dynamic>?})).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3470)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3438)
#2      ProgramCompiler._emitClassSignature (package:dev_compiler/src/kernel/compiler.dart:1713)
#3      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:1119)
#4      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:1001)
#5      List.forEach (dart:core-patch/growable_array.dart:421)
#6      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:940)
#7      List.forEach (dart:core-patch/growable_array.dart:421)
#8      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:629)
#9      IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:246)
#10     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:877)
<asynchronous suspension>
#11     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:693)
<asynchronous suspension>
#12     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1401)
<asynchronous suspension>
the Dart compiler exited unexpectedly.

**Comment by CarGuo** [comment]
@jones655 请确定本地 flutter sdk 为 3.29

**Comment by 17863966841** [comment]
去安全登陆的页面404呀

**Comment by CarGuo** [comment]
@17863966841 如上视频所示，你的怎么 404 ？

https://github.com/user-attachments/assets/be40dcb3-de9f-40c7-b4ce-e6664f9228cd

https://github.com/user-attachments/assets/b287cb99-57db-45f1-b9c3-77c3e2a457c1
