### ISSUE TITLE
在AS3.4下无法运行

### ISSUE THREAD

**Issue by shencang** [CarGuo/GSYGithubAppFlutter#409]
错误日志：
错误:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:86)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:214)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:73)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:12)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:74)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexBuilder.buildStarted(JavaBackwardReferenceIndexBuilder.java:40)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:358)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:229)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

as版本3.4，flutter版本1.6.1,已经配置ignoreconfig，已安装findbugs

**Comment by CarGuo** [comment]
我一到也是3.4，正常运行

**Comment by CarGuo** [comment]
你这个看起来像是环境问题，报错的都和项目无关

**Comment by shencang** [comment]
> 你这个看起来像是环境问题，报错的都和项目无关

谢谢你的回复。我在尝试找到这个问题的解决方案。

**Comment by shencang** [comment]
> 你这个看起来像是环境问题，报错的都和项目无关

您好。

经过修改环境，能够正确显示错误内容了：
```
Compiler message:
file:///D:/soft_work/flutter_s/flutter_1.6.1/.pub-cache/git/photo_view-1fc0effdb8269f4f6bb61186acb127890002b770/lib/photo_view.dart:381:5: Error: 'ImageStreamListener' isn't a type.
    ImageStreamListener listener = new ImageStreamListener(listenerSuccess);
    ^^^^^^^^^^^^^^^^^^^
file:///D:/soft_work/flutter_s/flutter_1.6.1/.pub-cache/git/photo_view-1fc0effdb8269f4f6bb61186acb127890002b770/lib/photo_view.dart:381:40: Error: Method not found: 'ImageStreamListener'.
    ImageStreamListener listener = new ImageStreamListener(listenerSuccess);
                                       ^^^^^^^^^^^^^^^^^^^
file:///D:/soft_work/flutter_s/flutter_1.6.1/.pub-cache/git/photo_view-1fc0effdb8269f4f6bb61186acb127890002b770/lib/photo_view.dart:381:59: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    ImageStreamListener listener = new ImageStreamListener(listenerSuccess);
```
也就是photo_view部分。
此时仍无法成功运行、
修改pubspec.yaml的photo_view
将
```dart
  photo_view:
    git:
    url: https://github.com/CarSmallGuo/photo_view.git
    ref: 1fc0effdb8269f4f6bb61186acb127890002b770

```
变更为上面dependencies下的第三方引用：
```
photo_view: ^0.3.3
```
就可以运行了。= =

**Comment by CarGuo** [comment]
昨晚更新了readme，flutter的新版本的 master分支修改了这个支持，所以flutter sdk要切换到master以后 flutter upgrade

**Comment by shencang** [comment]
> 昨晚更新了readme，flutter的新版本的 master分支修改了这个支持，所以flutter sdk要切换到master以后 flutter upgrade

Thanks♪(･ω･)ﾉ谢谢
