### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by MrWude** [CarGuo/GSYGithubAppFlutter#502]
Initializing hot reload...                                             ⡿I/flutter ( 4858): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4858): The following NoSuchMethodError was thrown building StreamBuilder<Store<GSYState>>(dirty, state:
I/flutter ( 4858): _StreamBuilderBaseState<Store<GSYState>, AsyncSnapshot<Store<GSYState>>>#dbb5e):
I/flutter ( 4858): The getter 'state' was called on null.
I/flutter ( 4858): Receiver: null
I/flutter ( 4858): Tried calling: state
I/flutter ( 4858): 
I/flutter ( 4858): Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
I/flutter ( 4858): be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
I/flutter ( 4858): 
I/flutter ( 4858): When the exception was thrown, this was the stack:
I/flutter ( 4858): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 4858): #1      FlutterReduxApp.build.<anonymous closure> (package:gsy_github_app_flutter/main.dart:66:27)
I/flutter ( 4858): #2      _StoreStreamListenerState.build.<anonymous closure> (package:flutter_redux/flutter_redux.dart)
I/flutter ( 4858): #3      StreamBuilder.build (package:flutter/src/widgets/async.dart:527:74)
I/flutter ( 4858): #4      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:131:48)
I/flutter ( 4858): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4039:27)
I/flutter ( 4858): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3933:15)
I/flutter ( 4858): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter ( 4858): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter ( 4858): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter ( 4858): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter ( 4858): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter ( 4858): #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter ( 4858): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter ( 4858): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter ( 4858): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter ( 4858): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
I/flutter ( 4858): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter ( 4858): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter ( 4858): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter ( 4858): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
I/flutter ( 4858): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter ( 4858): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter ( 4858): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter ( 4858): #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4246:5)
I/flutter ( 4858): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter ( 4858): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter ( 4858): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter ( 4858): #28     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter ( 4858): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:20)
I/flutter ( 4858): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 4858): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter ( 4858): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter ( 4858): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter ( 4858): #35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 4858): #36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 4858): #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 4858): (elided one frame from package dart:async-patch)
I/flutter ( 4858): 
I/flutter ( 4858): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by MrWude** [comment]
master分支

**Comment by MrWude** [comment]
flutter version v1.7.8解决了
