### ISSUE TITLE
扫码下载apk包，点击安装时报错：安装失败(-113)，请教什么问题

### ISSUE THREAD

**Issue by manburenshenglu** [CarGuo/GSYGithubAppFlutter#535]

**Comment by manburenshenglu** [comment]
08-15 14:21:28.438 17821-17821/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shuyu.gsygithub.gsygithubappflutter, PID: 17821
    java.lang.UnsatisfiedLinkError: Couldn't load flutter from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shuyu.gsygithub.gsygithubappflutter-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.shuyu.gsygithub.gsygithubappflutter-1, /vendor/lib, /system/lib]]]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:358)
        at java.lang.System.loadLibrary(System.java:526)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:122)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:99)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4455)
        at android.app.ActivityThread.access$1500(ActivityThread.java:147)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5135)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
        at dalvik.system.NativeStart.main(Native Method)
08-15 14:21:28.688 1035-17837/? E/ActivityThread: Failed to find provider info for com.leadcore.sdb
08-15 14:21:33.058 771-894/? E/lights: write_int failed to open /sys/class/leds/key-pad/brightness
08-15 14:21:41.028 208-17710/? E/mdb_debug: usb_linux_client.c:usb_read[L-304]: ERROR: fd = 16, n = -1: 5, I/O error
08-15 14:21:41.028 208-17710/? E/mdb_debug: transport_usb.c:remote_read[L-61]: remote usb: read terminated (message): 5, I/O error
08-15 14:21:41.028 208-17710/? E/mdb_debug: transport.c:output_thread[L-214]: usb_fd16: remote read failed for transport: 5, I/O error
08-15 14:21:41.028 208-17710/? E/mdb_debug: transport.c:output_thread[L-231]: usb_fd16: transport output thread is exiting: 5, I/O error
08-15 14:21:41.048 208-17709/? E/mdb_debug: transport.c:input_thread[L-279]: usb_fd16: transport input thread is exiting, fd 18
    : 0, Success
我换了一台测试机：红米2A Android4.4系统，安装倒是成功了，但是一运行就闪退，错误log如上

**Comment by CarGuo** [comment]
<img width="986" alt="image" src="https://user-images.githubusercontent.com/10770362/63076941-5466b800-bf69-11e9-952f-c7397a697b61.png">

因为我只打包了 64 位的 so

**Comment by manburenshenglu** [comment]
好的，谢谢楼主。我把楼主的的源码运行安装了
